# Schema for the configuration files of the Bootstrap Barrio Subtheme.

imaginelex.settings:
  type: theme_settings
  label: 'Imagine Lex settings'
  mapping:
    imaginelex_sidebar_position:
      type: text
      label: 'Sidebar Position'
    imaginelex_content_offset:
      type: integer
      label: 'Offset'
    imaginelex_sidebar_first_width:
      type: integer
      label: 'Width'
    imaginelex_sidebar_first_offset:
      type: integer
      label: 'Offset'
    imaginelex_sidebar_second_width:
      type: integer
      label: 'Width'
    imaginelex_sidebar_second_offset:
      type: integer
      label: 'Offset'
    imaginelex_footer_layout:
      type: text
      label: 'Layout'
    imaginelex_fluid_container:
      type: integer
      label: 'Enabled'
    imaginelex_button_size:
      type: text
      label: 'Size'
    imaginelex_button_outline:
      type: integer
      label: 'Button outline'
    imaginelex_navbar_top_position:
      type: text
      label: 'Position'
    imaginelex_navbar_top_color:
      type: integer
      label: 'Color'
    imaginelex_navbar_top_background:
      type: text
      label: 'Background'
    imaginelex_navbar_position:
      type: text
      label: 'Position'
    imaginelex_navbar_color:
      type: integer
      label: 'Color'
    imaginelex_navbar_background:
      type: text
      label: 'Background'
    imaginelex_anchors_fix:
      type: integer
      label: 'Enabled'
    imaginelex_anchors_smooth_scrolling:
      type: integer
      label: 'Enabled'
    imaginelex_forms_required_has_error:
      type: integer
      label: 'Enabled'
    imaginelex_forms_has_error_value_toggle:
      type: integer
      label: 'Enabled'
    imaginelex_forms_smart_descriptions:
      type: integer
      label: 'Enabled'
    imaginelex_forms_smart_descriptions_limit:
      type: integer
      label: 'Limit'
    imaginelex_forms_smart_descriptions_allowed_tags:
      type: text
      label: 'Allowed tags'
    imaginelex_popover_enabled:
      type: integer
      label: 'Enabled'
    imaginelex_popover_animation:
      type: integer
      label: 'Enabled'
    imaginelex_popover_html:
      type: integer
      label: 'Enabled'
    imaginelex_popover_placement:
      type: text
      label: 'Placement'
    imaginelex_popover_selector:
      type: text
      label: 'Selector'
    imaginelex_popover_trigger_autoclose:
      type: integer
      label: 'Enabled'
    imaginelex_popover_delay:
      type: integer
      label: 'Enabled'
    imaginelex_popover_trigger:
      type: mapping
      mapping:
        hover:
          type: integer
          label: 'Hover'
    imaginelex_tooltip_enabled:
      type: integer
      label: 'Enabled'
    imaginelex_tooltip_descriptions:
      type: integer
      label: 'Enabled'
    imaginelex_tooltip_descriptions_length:
      type: integer
      label: 'Length'
    imaginelex_tooltip_animation:
      type: integer
      label: 'Enabled'
    imaginelex_tooltip_html:
      type: integer
      label: 'Length'
    imaginelex_tooltip_delay:
      type: integer
      label: 'Enabled'
    imaginelex_popover_title:
      type: text
      label: 'Title'
    imaginelex_popover_content:
      type: text
      label: 'Content'
    imaginelex_tooltip_placement:
      type: text
      label: 'Placement'
    imaginelex_tooltip_container:
      type: text
      label: 'Container'
    imaginelex_tooltip_selector:
      type: text
      label: 'Selector'
    imaginelex_tooltip_trigger:
      type: mapping
      mapping:
        hover:
          type: text
          label: 'Hover'
    imaginelex_popover_container:
      type: text
      label: 'Container'