features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: themes/custom/imaginelex/logo.png
favicon:
  use_default: true
custom_css: 0
disable_google_fonts: 0
bootstrap_barrio_fluid_container: 1
bootstrap_barrio_region_clean_main_nav: 0
bootstrap_barrio_region_class_main_nav: row
bootstrap_barrio_region_clean_header: 1
bootstrap_barrio_region_class_header: ''
bootstrap_barrio_region_clean_help: 0
bootstrap_barrio_region_class_help: row
bootstrap_barrio_region_clean_breadcrumbs: 0
bootstrap_barrio_region_class_breadcrumbs: row
bootstrap_barrio_region_clean_title: 0
bootstrap_barrio_region_class_title: row
bootstrap_barrio_region_clean_content: 0
bootstrap_barrio_region_class_content: col-12
bootstrap_barrio_region_clean_sidebar: 0
bootstrap_barrio_region_class_sidebar: row
bootstrap_barrio_region_clean_footer: 0
bootstrap_barrio_region_class_footer: row
bootstrap_barrio_sidebar_position: left
bootstrap_barrio_content_offset: '0'
bootstrap_barrio_sidebar_collapse: 0
bootstrap_barrio_sidebar_first_width: '2'
bootstrap_barrio_sidebar_first_offset: '0'
bootstrap_barrio_sidebar_second_width: '2'
bootstrap_barrio_sidebar_second_offset: '0'
bootstrap_barrio_button: 0
bootstrap_barrio_button_size: ''
bootstrap_barrio_button_outline: 0
bootstrap_barrio_navbar_container: 0
bootstrap_barrio_navbar_toggle: navbar-toggleable-lg
bootstrap_barrio_navbar_top_navbar: 0
bootstrap_barrio_navbar_top_position: fixed-top
bootstrap_barrio_navbar_top_color: ''
bootstrap_barrio_navbar_top_background: ''
bootstrap_barrio_navbar_position: ''
bootstrap_barrio_navbar_color: ''
bootstrap_barrio_navbar_background: ''
bootstrap_barrio_messages_widget: alerts
bootstrap_barrio_radio: standard
bootstrap_barrio_checkbox: standard
bootstrap_barrio_select: standard
bootstrap_barrio_file: standard
bootstrap_barrio_navbar_top_affix: 1
bootstrap_barrio_navbar_affix: 0
bootstrap_barrio_sidebar_first_affix: 0
bootstrap_barrio_sidebar_second_affix: 0
bootstrap_barrio_scroll_spy: ''
bootstrap_barrio_google_fonts: ''
bootstrap_barrio_icons: ''
bootstrap_barrio_system_messages: ''
bootstrap_barrio_table_style: ''
bootstrap_barrio_table_hover: 0
bootstrap_barrio_table_head: ''
