<?php

use Drupal\node\Entity\Node;
use Drupal\Core\Form\FormStateInterface;


/**
 * populates alias field for policies
 */
function il_utils_post_update_8001() {
  $query = \Drupal::entityQuery('node')
    ->condition('type', 'policy')
    ->execute();

  foreach ($query as $nid) {
    $node = Node::load($nid);
    $alias = str_replace(' ', '-', strtolower($node->field_short_name->value));
    if (empty($node->path['alias'])) {
      $node->path->alias = '/' . $alias;
    }
    $node->save();
  };
}

/**
 * Implements hook_form_alter().
 */
function il_utils_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_general_page_form' || $form_id == 'node_general_page_edit_form') {
    $form['field_hero_image']['#states'] = [
      'visible' => [
        'select[name="field_hero_type"]' => ['value' => 'image'],
      ]
    ];
    $form['field_hero_vid']['#states'] = [
      'visible' => [
        'select[name="field_hero_type"]' => ['value' => 'video'],
      ],
    ];
  }

}
